[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$PrivateConfig,[switch]$TestMode,[string]$FixtureRoot,[string]$ExternalReadbackFile,[string]$ServiceReadbackFile)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
Import-Module (Join-Path $PSScriptRoot 'phase12b-host.psm1') -Force
Test-Phase12BTestAdapter -TestMode:$TestMode -FixtureRoot $FixtureRoot -ExternalReadbackFile $ExternalReadbackFile -ServiceReadbackFile $ServiceReadbackFile
$cfg=Read-Phase12BConfig $PrivateConfig;$h=$cfg.Host;$state=Get-Phase12BHostState -RuntimeRoot $h.runtime_root -ExecutionRoot $h.execution_root -HostId $h.host_id -ProfileRoot $h.profile_root -RunnerRoot $h.runner_root;$runtime=Read-Phase12BRuntime $h.runtime_root
$aclResult='PASS';foreach($path in @($h.runtime_root,$h.profile_root,$h.execution_root,$h.runner_root)){if(-not(Test-Path -LiteralPath $path -PathType Container) -or -not(Test-Phase12BAclPolicy -Acl (Get-Acl -LiteralPath $path))){$aclResult='FAIL';break}}
$localPass=$state -eq 'EXISTING' -and $aclResult -eq 'PASS';$lines=@();$externalPass=$true
$serviceRecords=if($ServiceReadbackFile){@(Get-Content -LiteralPath $ServiceReadbackFile -Raw|ConvertFrom-Json)}else{$null}
foreach($caller in $cfg.Callers){
  $safe=($caller.Repository -replace '[^A-Za-z0-9]','_').ToUpperInvariant();$identity=Get-Phase12BCallerRunnerIdentity -RunnerRoot $h.runner_root -RepositoryId $caller.RepositoryId;$root=$identity.RunnerDirectory;$marker=Test-Path -LiteralPath (Join-Path $root '.runner') -PathType Leaf;$service=if($ServiceReadbackFile){Get-Phase12BServiceForRunner -RunnerRoot $root -ServiceRecords $serviceRecords}else{Get-Phase12BServiceForRunner $root};$runnerName=$identity.RunnerName
  $external=$null
  try{$external=Get-Phase12BExternalCallerState -Config $cfg -Caller $caller -TestMode:$TestMode -FixtureRoot $FixtureRoot -ExternalReadbackFile $ExternalReadbackFile;$x=Test-Phase12BExternalCallerState -Config $cfg -Caller $caller -External $external -RunnerName $runnerName}catch{$x=[pscustomobject]@{Repository='FAIL';Runner='FAIL';Secret='FAIL';Iam='FAIL';Workflow='FAIL';Wif='FAIL';Branch='FAIL';All=$false}}
  $serviceOk=$service.Classification -eq 'EXISTING' -and $service.ServiceName -ieq $identity.ServiceName;$callerOk=$marker -and $serviceOk -and $x.All;if(-not $callerOk){$localPass=$false};if(-not $x.All){$externalPass=$false}
  $branchReadback=if($null -ne $external){[string]$external.DefaultBranch}else{'UNKNOWN'}
  $lines += "CALLER_${safe}_CONFIG=PASS"; $lines += "CALLER_${safe}_REPOSITORY_ID=$($x.Repository)"; $lines += "CALLER_${safe}_WORKFLOW_BRANCH=$branchReadback"; $lines += "CALLER_${safe}_RUNNER_ROOT=$root"; $lines += "CALLER_${safe}_RUNNER=$($x.Runner)"; $lines += "CALLER_${safe}_RUNNER_MARKER=$(if($marker){'PASS'}else{'FAIL'})"; $lines += "CALLER_${safe}_WINDOWS_SERVICE_NAME=$($service.ServiceName)"; $lines += "CALLER_${safe}_WINDOWS_SERVICE_EXPECTED=$($service.ExpectedServiceName)"; $lines += "CALLER_${safe}_WINDOWS_SERVICE_PATH=$($service.PathName)"; $lines += "CALLER_${safe}_WINDOWS_SERVICE_IDENTITY=$($service.Identity)"; $lines += "CALLER_${safe}_WINDOWS_SERVICE_STATE=$($service.State)"; $lines += "CALLER_${safe}_WINDOWS_SERVICE=$(if($serviceOk){'PASS'}else{'FAIL'})"; $lines += "CALLER_${safe}_SECRET_METADATA=$($x.Secret)"; $lines += "CALLER_${safe}_IAM=$($x.Iam)"; $lines += "CALLER_${safe}_CALLER_WORKFLOW_BRANCH=$($x.Branch)"; $lines += "CALLER_${safe}_CALLER_WORKFLOW=$($x.Workflow)"; $lines += "CALLER_${safe}_WIF=$($x.Wif)"
}
$final=if($localPass -and $externalPass){'PASS'}else{'STOP'}
@('HOST_VERIFY',"RESULT=$final",'CONFIG=PASS',"HOST_RUNTIME=$state",("EXECUTION_AREA={0}" -f $(if(Test-Path -LiteralPath $h.execution_root){'PASS'}else{'FAIL'})),("MARKER={0}" -f $(if(Test-Path -LiteralPath (Join-Path $h.execution_root '.codex-automation-managed')){'PASS'}else{'FAIL'})),("SCHEMA={0}" -f $(if($runtime -and $runtime.schema -eq 1){'PASS'}else{'FAIL'})),"SERVICE_IDENTITY=$($h.service_identity)",("PROFILE={0}" -f $(if(Test-Path -LiteralPath $h.profile_root){'PASS'}else{'FAIL'})),"ACL=$aclResult","MUTEX_POLICY=$($h.serialization)",("WIF={0}" -f $(if($externalPass){'PASS'}else{'FAIL'})),'CALLER_CONFIG=PASS',("REPOSITORY_ID={0}" -f $(if($externalPass){'PASS'}else{'FAIL'})),("SECRET_METADATA={0}" -f $(if($externalPass){'PASS'}else{'FAIL'})),("IAM={0}" -f $(if($externalPass){'PASS'}else{'FAIL'})),'RUNNER=PER_CALLER_READBACK','WINDOWS_SERVICE=PER_CALLER_READBACK',("CALLER_WORKFLOW={0}" -f $(if($externalPass){'PASS'}else{'FAIL'})),'SECRET_PAYLOAD=NOT_READ',"PRIVATE_CONFIG=$PrivateConfig",("NEXT_ACTION={0}" -f $(if($final -eq 'PASS'){'NONE'}else{'INVESTIGATE'}))) + $lines -join "`n"
if($final -ne 'PASS'){exit 2}
